---
title: "Visualizing and processing result -- Comment"
author:
- name: Hervé Guillon
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
vignette: >
  %\VignetteIndexEntry{Visualizing and processing result -- Comment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: bibliography.bib
---

# Summary

In general, $w_x$, $w_y$, $1/f_c$, $r_c$ and $\xi$ have some clear spatial patterns and increases with scales as expected.
This fact that this spatial pattern is consistent indicates that there is no issues with the assignment of the raster cells values.
$\alpha$ and $\zeta$ variables have little to no spatially consistent signal even if their values and evolution are within the range of what is expected for the different landscape.
The $x$ direction seems to correspond most often with the direction parallel with the main large scale undulations but only at a 60-75% average rate which decreases with between $\alpha_1$ and $\alpha_2$.
Most often, $\alpha_x$ > $\alpha_y$


# Gabilan Mesa

## Maps

- $\beta_2$, $\alpha_{1,x}$, $\alpha_{1,y}$, $\alpha_{2,x}$, $\alpha_{2,y}$, $\zeta_1$, $\zeta_2$ have no clear spatial pattern
- $w_x$, $w_y$, $1/f_c$, $r_c$ and $\xi$ have clear spatial patterns

## Distribution plot

- $\vert\beta_2\vert$ clearly decreases with scale
- $\alpha_{1,x}$ weakly decreases with scale
- $\alpha_{i,i}$, $\zeta_1$, are roughly constant across scales
- $w_x$, $w_y$, $1/f_c$, $r_c$ and $\xi$ increases with scale

## $x$ and $y$ directions

- $\hat{x}$ has a greater value of $\alpha_1$ (69%) 
- $\hat{x}$ has a greater value of $\alpha_2$ (59%) 
- $\hat{x}$ has a greater value of $w$ (64%)

# Yosemite Valley

## Maps

- $\beta_2(800)$, $\alpha_1(800)$ have some clear spatial pattern but it rapidly disappears
- $w_x$ and $w_y$ have clear spatial patterns

## Distribution plots

- $\vert\beta_2\vert$ clearly decreases with scale
- $w_x$, $w_y$, $1/f_c$, $r_c$ and $\xi$ increases with scale

## $x$ and $y$ directions

- $\hat{x}$ has a greater value of $\alpha_1$ (73%) 
- $\hat{x}$ has a greater value of $\alpha_2$ (68%) 
- $\hat{x}$ has a greater value of $w$ (75%)


# Modoc Plateau

## Maps

- no clear spatial pattern

## Distribution plots

- $\vert\beta_2\vert$ clearly decreases with scale
- $w_x$, $w_y$, $1/f_c$ increases with scale

## $x$ and $y$ directions

- $\hat{x}$ has a greater value of $\alpha_1$ (59%) 
- $\hat{x}$ has a greater value of $\alpha_2$ (54%) 
- $\hat{x}$ has a greater value of $w$ (60%)