version: 2.1
orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
      - checkout
      # - run:
      #     name: Initializing temp dir for libraries
      #     command: |
      #       echo $HOME
      #       mkdir $HOME/site-library
      - run: 
          name: Install packages
          command: |
            sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
            sudo apt-get -q update
            sudo apt-get -y install libgdal-dev libgeos-dev libproj-dev 
            sudo apt-get -y install libharfbuzz-dev libfribidi-dev
            sudo apt-get -y install libmagick++-dev
            sudo apt-get -y install libglu1-mesa-dev freeglut3-dev mesa-common-dev
            sudo apt-get -y install git libssl-dev ssh texlive-latex-base texlive-fonts-recommended libcurl4-openssl-dev libxml2-dev
            sudo apt-get -y install pandoc pandoc-citeproc
            sudo apt-get -y install tree
      - run:
          name: Install R
          command: |
            sudo apt-get -y install r-base
            sudo apt-get -y install r-cran-rgl
      - run:
          name: Create local library folder
          command: |
            R -e "dir.create(path = Sys.getenv('R_LIBS_USER'), showWarnings = FALSE, recursive = TRUE)"
      - restore_cache:
          keys: 
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
      # - run:
      #     name: Restoring cached libraries from HOME
      #     command: sudo cp -r $HOME/site-library/ /usr/local/lib/R/site-library/            
      - run:
          name: Install devtools and Roxygen
          command: |
            R -e "install.packages(c('devtools', 'roxygen2', 'pkgdown'), lib = Sys.getenv('R_LIBS_USER'))"
      - run:
          name: Install package dependencies
          command: R -e "withr::with_libpaths(Sys.getenv('R_LIBS_USER'), devtools::install_deps(dep = TRUE))"
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
          paths:
            - ~/R   
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
      - run:
          name: Build docs
          command: |
            R -e "pkgdown::build_site()"
      - run:  
          name: Calculate code coverage
          command: |
            sudo Rscript -e "covr::codecov()"
            bash <(curl -s https://codecov.io/bash)
      - gh-pages/deploy:
          build-dir: docs
