version: 2.1

executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
  docker-latest:
    docker:
      - image: hrvg/statisticalRoughness:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASS
  docker-develop:
    docker:
      - image: hrvg/statisticalRoughness:develop
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASS

orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

jobs:
  docker-build-publish-latest:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  docker-build-publish-develop:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Docker login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:develop -f "Dockerfile-develop" .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker push $IMAGE_NAME:develop
  r-build-latest:
    executor: docker-latest
    steps:
      - checkout
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
      - run:
          name: Calculate code coverage
          command: R -e "covr::codecov()"
      - run:
          name: Build docs
          command: R -e "pkgdown::build_site()"
      - gh-pages/deploy:
          build-dir: docs
  r-build-develop:
    executor: docker-develop
    steps:
      - checkout
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
      - run:
          name: Calculate code coverage
          command: R -e "covr::codecov()"
  r-unit-test:
    executor: docker-develop
    steps:
      - checkout
      - run:
          name: Unit tests
          command: |
            R -e "devtools::test(stop_on_failure = TRUE)"

workflows:
  build-main:
    jobs:
      - docker-build-publish-latest:
          context:
            - docker-credentials
          filters:
            branches:
              only: main
      - r-build-latest:
          context:
            - docker-credentials
          requires: 
            - docker-build-publish-latest
          filters:
            branches:
              only: main
  build-develop:
    jobs:
      - docker-build-publish-develop:
          context:
            - docker-credentials
          filters:
            branches:
              only: develop
      - r-build-develop:
          context:
            - docker-credentials
          requires: 
            - docker-build-publish-develop
          filters:
            branches:
              only: 
                - develop
      - r-unit-test:
          context:
            - docker-credentials
          filters:
            branches:
              only: 
                - /^feature-.*/
                - /^experiment-.*/
      - r-build-develop:
          context:
            - docker-credentials
          filters:
            branches:
              only: 
                - /^release-.*/
