version: 2.1
jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
      - checkout
      - run: 
          name: "Installing packages"
          command: |
            sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
            sudo apt-get -q update
            sudo apt-get -y install libgdal-dev libgeos-dev libproj-dev 
            sudo apt-get -y install libharfbuzz-dev libfribidi-dev
            sudo apt-get -y install libmagick++-dev
            sudo apt-get -y install libglu1-mesa-dev freeglut3-dev mesa-common-dev
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz