version: 2.1
orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
      - checkout
      - run:
          name: Initializing temp dir for libraries
          command: mkdir $HOME/site-library
      - restore_cache:
          keys: 
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
      - run: 
          name: Install packages
          command: |
            sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
            sudo apt-get -q update
            sudo apt-get -y install libgdal-dev libgeos-dev libproj-dev 
            sudo apt-get -y install libharfbuzz-dev libfribidi-dev
            sudo apt-get -y install libmagick++-dev
            sudo apt-get -y install libglu1-mesa-dev freeglut3-dev mesa-common-dev
            sudo apt-get -y install git libssl-dev ssh texlive-latex-base texlive-fonts-recommended libcurl4-openssl-dev libxml2-dev
            sudo apt-get -y install pandoc pandoc-citeproc
      - run:
          name: Install R
          command: |
            sudo apt-get -y install r-base
            sudo apt-get -y install r-cran-rgl
      - run:
          name: Restoring cached libraries from HOME
          command: sudo cp -r $HOME/site-library/ /usr/local/lib/R/site-library/            
      # - run:
      #     name: Install devtools and Roxygen
      #     command: sudo R -e "install.packages(c('devtools', 'roxygen2'))"
      # - run:
      #     name: Install package dependencies
      #     command: sudo R -e "devtools::install_deps(dep = TRUE)"
      # - run:
      #     name: Build package
      #     command: R CMD build .
      # - run:
      #     name: Check package
      #     command: R CMD check *tar.gz
      # - run:
      #     name: Build docs
      #     command: sudo Rscript -e "pkgdown::build_site()"
      # - run:  
      #     name: Calculate code coverage
      #     command: |
      #       sudo Rscript -e "covr::codecov()"
      #       bash <(curl -s https://codecov.io/bash)


      - run:
          name: Saving libraries into HOME
          command: sudo cp -r /usr/local/lib/R/site-library/ $HOME/site-library/        
      - run: 
          name: Checking file structure
          command: |
            echo $(pwd)
            echo $(ls $HOME/site-library)
            echo $(ls /usr/local/lib/R/site-library)
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
          paths:
            - $HOME/site-library    

workflows:
  build_deploy:
    jobs:
      - build
      - gh-pages/deploy:
          build-dir: docs
          requires:
            - build
          ssh-fingerprints: '8e:85:be:3c:e5:f4:5d:1b:90:23:95:59:f3:ce:cb:c0'