test_that("get_zeta_df works", {
	test_path <- system.file("extdata/rasters/", package = "statisticalRoughness")
	test_raster <- terra::rast(file.path(test_path, "gabilan_mesa.tif"))
	test_raster2 <- terra::rast(file.path(test_path, "yosemite.tif"))
	test_tiles <- terra::aggregate(test_raster, fact = 100)
	test_tiles_vect <- terra::as.polygons(test_tiles, dissolve = FALSE)
	results <- get_zeta_df(test_raster, test_tiles)
	expect_is(results, 'data.frame')
	expect_equal(nrow(results), terra::ncell(test_tiles))
	expect_error(get_zeta_df("test_raster", test_tiles), "invalid class: DEM is not of class 'SpatRaster'")
	expect_error(get_zeta_df(test_raster, "test_tiles"), "invalid class: tiles is not of class 'SpatRaster' or 'SpatVector'")
	expect_error(get_zeta_df(test_raster, test_tiles, crs_ref = "crs_ref"), "invalid class: crs_ref is not of class 'CRS'")
	expect_error(get_zeta_df(test_raster, test_tiles, vertical_accuracy = "abc"), "invalid class: vertical_accuracy is not of class 'numeric'")
	expect_error(get_zeta_df(test_raster, terra::disaggregate(test_raster, fact = 2)), "There are more tiles than cells in your raster.")
	expect_error(get_zeta_df(test_raster, terra::aggregate(test_raster2, fact = 100)), "There are no tiles covering your raster.")
})
